language: java
jdk: oraclejdk8
before_script:
- export ROOT_PROJ="$(pwd)"
- bash importApp/scripts/travis-sphere-credentials.sh
script:
  - cd importApp
  - export PAYLOAD_FILE="$(pwd)/travis-payload.json"
  - export MAVEN_OPTS="-Xmx512m"
  - mvn spring-boot:run -Dstart-class=com.commercetools.dataimport.all.PayloadJobMain
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    on_success: change
    on_failure: change
