language: java
jdk: oraclejdk8
before_script: bash importApp/scripts/travis-sphere-credentials.sh
script:
  - cd importApp
  - mvn test pre-integration-test integration-test post-integration-test
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    on_success: change
    on_failure: change