sudo: required
services:
- docker
before_script:
- bash importApp/scripts/travis-sphere-credentials.sh
script:
  - docker run -v $PWD:/wd msct/jdk8 /bin/sh -c "cd /wd/importApp && export PAYLOAD_FILE=/wd/importApp/travis-payload.json && export MAVEN_OPTS='-Xmx1024m' && export ROOT_PROJ='/wd' && ./mvnw spring-boot:run -Dstart-class=com.commercetools.dataimport.all.PayloadJobMain"
notifications:
  email:
    on_success: change
    on_failure: change
